const applications = [
  { key: "first-name", ch: "first_name" },
  { key: "middle-name", ch: "middle_name" },
  { key: "last-name", ch: "last_name" },
  { key: "current-occupation", ch: "last-name" },
  { key: "length-of-experience", ch: "last-name" },
  { key: "area-of-expertise-specialisation", ch: "last-name" },
  { key: "languages", ch: "last-name" },
  { key: "clients-types", ch: "last-name" },
  { key: "therapeutic-approaches", ch: "last-name" },
  { key: "current--last-place-of-practice", ch: "last-name" },
  { key: "educational-qualifications", ch: "last-name" },
  { key: "professional-certifications", ch: "last-name" },
  { key: "professional-memberships", ch: "last-name" },
  { key: "specific-groups", ch: "last-name" },
  { key: "not-to-work-with", ch: "last-name" },
  { key: "preferred-modes-of-communication", ch: "last-name" },
  { key: "approximate-availability-hours-per-week", ch: "last-name" },
];
